### PR TITLE
Add sed to remove NOTA's from Spain data

### PR DESCRIPTION
**Pull request by aramse**

### CODE REVIEW

**Comment by boogheta** [comment]
Hi again and thanks for the proposal.
Although, the spanish notes are currently being handled by filtering them out in the processing part [here](https://github.com/boogheta/coronavirus-countries/blob/master/bin/export-main-countries.py#L359) and I'd prefer to keep source data files untouched as much as possible.
I understand the idea and agrees with it, but I would rather like to remain as such, and make a new file without the notes using your sed command to publish another file instead of editing the original one if you could.

**Comment by boogheta** [comment]
Also, I haven't properly investigated it yet, but the notes actually say they changed the way data is published now and that data is not cumulative anymore but only daily rates, which would mean the data presented for spain is wrong and bugged and this file would need some preprocessing, in which case having a second file without the notes would definitely make more sense.

**Comment by aramse** [comment]
Ah didn't catch that filter/lambda command, makes sense! Sure thing, I'll update it to output to a `spain.csv` file (similar to how is done for uk and germany).

**Comment by boogheta** [comment]
Yes that would be perfect, thanks again!

**Pull request merged**
